import { useState, useCallback } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { AppContainer } from '../styles/home.styles'
import { ThemeProvider, DefaultTheme } from 'styled-components'
import { light } from '../styles/themes/light'
import { dark } from '../styles/themes/dark'
import { usePersistedState } from '../utils/usePersistedState'

import Header from '../components/header'
import BookList from '../components/book-list'


const Home: NextPage = () => {
  const [theme, setTheme] = usePersistedState<DefaultTheme>('theme', light)

  const toggleTheme = useCallback(() => {
    setTheme(theme.title === 'light' ? dark : light) 
  }, [theme]) 

  return (
    <ThemeProvider theme={theme}>
      <AppContainer>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        
        </Head>
        <Header toggleTheme={toggleTheme}/>
        <BookList />
    </AppContainer>
    </ThemeProvider>
  )
}

export default Home
