import { useState, useCallback } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { AppContainer } from '../styles/home.styles'
import { ThemeProvider, DefaultTheme } from 'styled-components'
import { light } from '../styles/themes/light'
import { dark } from '../styles/themes/dark'
import { usePersistedState } from '../utils/usePersistedState'

import Header from '../components/header'
import BookList from '../components/book-list'
import AddBookSection from '../components/add-books-section'
import Modal from '../components/modal'


const Home: NextPage = () => {
  const [theme, setTheme] = usePersistedState<DefaultTheme>('theme', light)
  const [showModal, setShowModal] = useState(false)

  const toggleTheme = useCallback(() => {
    setTheme(theme.title === 'light' ? dark : light) 
  }, [theme]) 

  const handleShowModal = useCallback((isActive: boolean) => {
    setShowModal(isActive)
  }, [])

  return (
    <ThemeProvider theme={theme}>
      <AppContainer>
        <Head>
          <title>My Books</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        
        </Head>
        <Header toggleTheme={toggleTheme}/>
        <AddBookSection handleShowModal={() => handleShowModal(true)}/>
        <BookList />
        <Modal showModal={showModal} handleShowModal={() => handleShowModal(false)}/>
    </AppContainer>
    </ThemeProvider>
  )
}

export default Home
