import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import styled from 'styled-components'

const Testing  = styled.div`
  width: 300px;
  height: 200px;
  background-color: #ff4;
  padding:10px;
`;

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <p>Hellow World</p>
     <Testing>oo</Testing>
    </div>
  )
}

export default Home
